### ISSUE TITLE
TypeError: Cannot read property 'browser' of undefined

### ISSUE THREAD

**Issue by bdbogjoe** [jhipster/consul-config-loader#20]
I setup one docker-compose like this : 

```
consul-config-loader:
    image: jhipster/consul-config-loader
    volumes:
      - ./config:/config
    environment:
      CONFIG_MODE: filesystem
      INIT_SLEEP_SECONDS: 5
      CONSUL_URL: consul-server-bootstrap
      CONSUL_PORT: 8500
```

but i have this error in logs : 

```
----------------------------------------------------------------------
    Starting Consul Config Loader in filesystem mode
----------------------------------------------------------------------
    Loading config files in Consul K/V Store from the filesystem
    Add or edit properties files in '/config' to have them
    automatically reloaded into Consul
    Consul UI: http://consul-server-bootstrap:8500/ui/#/dc1/kv/config/
----------------------------------------------------------------------
   Consul Config reloaded
Watching config/**
/usr/lib/node_modules/simplywatch/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^
TypeError: Cannot read property 'browser' of undefined
    at Task.<anonymous> (/usr/lib/node_modules/simplywatch/node_modules/simplyimport/lib/task/init.coffee:40:24)
    at Task.<anonymous> (/usr/lib/node_modules/simplywatch/node_modules/simplyimport/lib/task/init.coffee:49:8)
    at Task.tryCatcher (/usr/lib/node_modules/simplywatch/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/simplywatch/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/simplywatch/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/simplywatch/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/simplywatch/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/usr/lib/node_modules/simplywatch/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/lib/node_modules/simplywatch/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/lib/node_modules/simplywatch/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/simplywatch/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

The config is uploaded, but seems issue while watching changes

**Comment by morganzhh** [comment]
Got the same error using image from dockerhub. Building image locally solved this issue.  ``Simplywatch`` might update its npm release

```
npm install -g simplywatch
```

**Comment by morganzhh** [comment]
Changing version of ``simplewatch`` to ``2.5.7`` solved this issue:

```diff
diff --git a/Dockerfile b/Dockerfile
index 90a3471..3e69bee 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -3,7 +3,7 @@ MAINTAINER Pierre Besson https://github.com/PierreBesson

 RUN apk --update add nodejs git openssh curl bash inotify-tools jq && \
     rm -rf /var/cache/apk/* && \
-    npm install -g simplywatch && \
+    npm install -g simplywatch@2.5.7 && \
     npm install -g git2consul@0.12.13 && \
     mkdir -p /etc/git2consul.d

```

**Comment by bdbogjoe** [comment]
thanks, i will apply this patch

**Comment by bdbogjoe** [comment]
great works fine, @PierreBesson possible to have a fix for this ?

**Comment by PierreBesson** [comment]
@bdbogjoe Please submit a Pull request, I will merge and release right away.

**Comment by bdbogjoe** [comment]
@morganzhh can you do it ? because you found the solution ;)

**Comment by PierreBesson** [comment]
The release is coming soon. Thanks @bdbogjoe !

**Comment by PierreBesson** [comment]
This is released and published to docker hub. PR on the generator opened: https://github.com/jhipster/generator-jhipster/pull/11621
